rm -r mpi_simple.o*
rm -r mpi_simple.e*
rm -r seq_simple.o*
rm -r seq_simple.e*
rm -r spmv_simple.o*
rm -r spmv_simple.e*
rm -r omp_spmv.o*
rm -r omp_spmv.e*
rm -r omp_aff.o*
rm -r omp_aff.e*
rm -r mpijob.o*
rm -r mpijob.e*
rm -r genMat.o*
rm -r genMat.e*
